default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 5598
  host: localhost

development:
  <<: *default
  database: Animebd_d

test:
  <<: *default
  database: Animebd_t

production:
  <<: *default
  database: Animebd_d
  username: postgres
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
